version: '3.7'

services:
  database:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - database-storage:/var/lib/postgresql/data
    build: .
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433

volumes:
  database-storage: